DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;
DROP TABLE IF EXISTS conversations CASCADE;
DROP TABLE IF EXISTS chats CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  lng NUMERIC NOT NULL,
  lat NUMERIC NOT NULL
);


CREATE TABLE profiles (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id),
  pet_name VARCHAR(255) NOT NULL,
  size VARCHAR(255) NOT NULL,
  breed VARCHAR(255) NOT NULL,
  species VARCHAR(255) NOT NULL,
  age INTEGER NOT NULL,
  picture VARCHAR(225)
);

CREATE TABLE chats (
  id SERIAL PRIMARY KEY NOT NULL,
  message TEXT NOT NULL,
  message_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER REFERENCES users(id)
);

CREATE TABLE conversations (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id),
  chat_id  INTEGER REFERENCES chats(id)
);